### ISSUE TITLE
Joining forces

### ISSUE THREAD

**Issue by chippmann** [raniejade/godot-kotlin#1]
@piiertho and I are working together on the same topic as you in another project.
Main-Project: https://github.com/MrAkakuy/kotlin-godot-wrapper
Our Fork: https://github.com/utopia-rise/kotlin-godot-wrapper
Maybe we can join forces and develop a wrapper together?
We are currently refactoring the code generation but the project is working already.
I think together we could make a great wrapper.

Our plan for the future is to refactor the code generation in that project, and simplify the registering process for the user by annotation processing through a kotlin compiler plugin (plugin done, code generation in progress).

**Comment by raniejade** [comment]
Hey! Interesting idea, but at the moment I would like to experiment/play around with this project a bit more. Based from what you said, I think how we envision the Kotlin binding is very different. I'm trying to avoid annotation processing and implementing a compiler plugin, so I'm just rely on language features available for now.

**Comment by chippmann** [comment]
I'm very interested in how you (maybe) will achieve the classes registration with just language features.
I will follow your progress with great interest. Once you have a solution, we can talk again if you want and then maybe join forces.
Until then, have fun and make good progress. :-)

**Comment by raniejade** [comment]
> I'm very interested in how you (maybe) will achieve the classes registration with just language features.

Just manually for now, I don't think it's a big blocker to a good binding.
